<?php
/**
 * MetaformTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Metatavu\Metaform
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Metaform REST API
 *
 * REST API for Metaform
 *
 * OpenAPI spec version: 0.0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Metatavu\Metaform;

/**
 * MetaformTest Class Doc Comment
 *
 * @category    Class */
// * @description Metaform
/**
 * @package     Metatavu\Metaform
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MetaformTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Metaform"
     */
    public function testMetaform()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "replyStrategy"
     */
    public function testPropertyReplyStrategy()
    {
    }

    /**
     * Test attribute "exportThemeId"
     */
    public function testPropertyExportThemeId()
    {
    }

    /**
     * Test attribute "allowAnonymous"
     */
    public function testPropertyAllowAnonymous()
    {
    }

    /**
<<<<<<< HEAD
     * Test attribute "allowDrafts"
     */
    public function testPropertyAllowDrafts()
    {
    }

    /**
=======
>>>>>>> 7fc12be5c5ace6aa3686ee1f7dc2d66a14aca476
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "sections"
     */
    public function testPropertySections()
    {
    }
}
